### ISSUE TITLE
Failed to activate the rustfmt package

### ISSUE THREAD

**Issue by cornelius-dol** [xgdapg/atom-rustfmt#8]
[Enter steps to reproduce:]

1. Attempt to install the package.

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [rustfmt](https://github.com/xgdapg/atom-rustfmt) package 0.1.3

### Stack Trace

Failed to activate the rustfmt package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1175864)
    at CompositeDisposable.add (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1176832)
    at Object.activate (/packages/rustfmt/lib/rustfmt.js:22:28)
    at Package.activateNow (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017814)
    at measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017226)
    at Package.measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3014857)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017086)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017029)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382643)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:899185
    at r (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:893791)
    at o (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -2:05.7.0 command-palette:toggle (input.hidden-input)
     -1:14.8.0 editor:consolidate-selections (input.hidden-input)
     -1:14.8.0 core:cancel (input.hidden-input)
     -1:14 editor:scroll-to-cursor (input.hidden-input)
  2x -1:08.5.0 key-binding-resolver:toggle (input.hidden-input)
     -1:06.8.0 settings-view:open (input.hidden-input)
     -1:00.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-overtype-mode 0.4.0 
autosave-onchange 1.5.1 
block-comment 0.4.3 
color-picker 2.3.0 
column-select 1.0.1 
css-declaration-sorter 1.2.3 
ctrl-dir-scroll 0.2.5 
file-templates 0.2.0 
highlight-line 0.12.0 
justright-latte-syntax 0.1.0 
justright-latte-ui 0.1.0 
language-batchfile 0.7.5 
language-ini 1.20.0 
language-rust 0.4.12 
linter-rust 1.0.1 
markdown-preview-plus 3.7.1 
multi-cursor-plus 1.2.0 
pigments 0.40.2 
process-palette 0.17.0 
project-manager 3.3.6 
rustfmt 0.1.3 
sort-lines 0.18.0 
sync-settings 0.8.6 
tree-view-auto-collapse 1.0.2 
tree-view-sort 0.11.1 
```

**Comment by cornelius-dol** [comment]
Atom. Ha ha! Another embrace, extend, and extinguish successfully executed by Microsoft.
